# Generated by Django 4.2 on 2024-12-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                default="profiles/default_image.jpg", upload_to="profiles/"
            ),
        ),
    ]
