# Generated by Django 4.2 on 2024-12-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="see_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
